name: 构建测试

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: 赋予 gradlew 可执行权限
      run: chmod +x gradlew

    - name: 获取 build.gradle.kts 的环境变量
      run: |
        VERSION=$(grep "versionName" build.gradle.kts | sed -n 's/.*versionName "\([^"]*\)".*/\1/p')
        echo "VERSION=$VERSION" >> $GITHUB_ENV


    - name: 得到本次提交 SHA 短号
      id: short_sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: 构建
      run: ./gradlew build
